/// Static language options for Known Languages multi-select (value => label).
/// Matches backend profile form options.
const Map<String, String> kLanguageOptions = {
  'afrikaans': 'Afrikaans',
  'albanian': 'Albanian',
  'amharic': 'Amharic',
  'arabic': 'Arabic',
  'armenian': 'Armenian',
  'assamese': 'Assamese',
  'azerbaijani': 'Azerbaijani (Azeri)',
  'bassa': 'Bassa',
  'belarusian': 'Belarusian',
  'bengali': 'Bengali',
  'bosnian': 'Bosnian',
  'braille': 'Braille',
  'bulgarian': 'Bulgarian',
  'burmese': 'Burmese',
  'cambodian': 'Cambodian',
  'cape_verde_creole': 'Cape Verde Creole',
  'cebuano': 'Cebuano',
  'central_kurdish': 'Central Kurdish',
  'cherokee': 'Cherokee',
  'chinese': 'Chinese',
  'chuukese': 'Chuukese',
  'croatian': 'Croatian',
  'czech': 'Czech',
  'danish': 'Danish',
  'dari': 'Dari',
  'dutch': 'Dutch',
  'english': 'English',
  'estonian': 'Estonian',
  'farsi': 'Farsi (Persian)',
  'finnish': 'Finnish',
  'flemmish': 'Flemmish',
  'french': 'French',
  'fulani': 'Fulani',
  'galician': 'Galician',
  'georgian': 'Georgian',
  'german': 'German',
  'greek': 'Greek',
  'gujarati': 'Gujarati',
  'haitian_creole': 'Haitian Creole',
  'hakha_chin': 'Hakha Chin',
  'hakka': 'Hakka (Chinese)',
  'hausa': 'Hausa',
  'hebrew': 'Hebrew',
  'hindi': 'Hindi',
  'hmong': 'Hmong',
  'hungarian': 'Hungarian',
  'icelandic': 'Icelandic',
  'igbo': 'Igbo/Ibo',
  'ilocano': 'Ilocano',
  'ilonggo': 'Ilonggo (Hiligaynon)',
  'indonesian': 'Indonesian',
  'irish': 'Irish',
  'isixhosa': 'isiXhosa',
  'isizulu': 'isiZulu',
  'italian': 'Italian',
  'japanese': 'Japanese',
  'javanese': 'Javanese',
  'kannada': 'Kannada',
  'karen': 'Karen',
  'kazakh': 'Kazakh',
  'khmer': 'Khmer',
  'kiche': "K'iche'",
  'kinyarwanda': 'Kinyarwanda',
  'kirundi': 'Kirundi',
  'kiswahili': 'KiSwahili',
  'konkani': 'Konkani',
  'korean': 'Korean',
  'kurdish': 'Kurdish',
  'kyrgyz': 'Kyrgyz/Kirgiz',
  'lao': 'Lao (Laotian)',
  'latvian': 'Latvian',
  'lithuanian': 'Lithuanian',
  'luxembourgish': 'Luxembourgish',
  'macedonian': 'Macedonian',
  'malay': 'Malay',
  'malayalam': 'Malayalam',
  'maltese': 'Maltese',
  'mandinka': 'Mandinka',
  'maori': 'Maori',
  'marathi': 'Marathi',
  'marshallese': 'Marshallese',
  'mien': 'Mien',
  'mongolian': 'Mongolian',
  'montenegrin': 'Montenegrin',
  'navajo': 'Navajo',
  'nepali': 'Nepali',
  'norwegian': 'Norwegian',
  'odia': 'Odia',
  'oromo': 'Oromo',
  'pashto': 'Pashto',
  'persian': 'Persian',
  'polish': 'Polish',
  'portuguese': 'Portuguese',
  'punjabi': 'Punjabi',
  'quechua': 'Quechua',
  'rohingya': 'Rohingya',
  'romanian': 'Romanian',
  'russian': 'Russian',
  'scottish_gaelic': 'Scottish Gaelic',
  'serbian': 'Serbian',
  'sesotho_sa_leboa': 'Sesotho sa Leboa',
  'setswana': 'Setswana',
  'sindhi': 'Sindhi',
  'sinhala': 'Sinhala',
  'slovak': 'Slovak',
  'slovenian': 'Slovenian',
  'somali': 'Somali',
  'spanish': 'Spanish',
  'swahili': 'Swahili',
  'swedish': 'Swedish',
  'tagalog': 'Tagalog',
  'tajik': 'Tajik',
  'tamil': 'Tamil',
  'tatar': 'Tatar',
  'telugu': 'Telugu',
  'thai': 'Thai',
  'tibetan': 'Tibetan',
  'tigrinya': 'Tigrinya',
  'turkish': 'Turkish',
  'turkmen': 'Turkmen',
  'ukrainian': 'Ukrainian',
  'urdu': 'Urdu',
  'uzbek': 'Uzbek',
  'valencian': 'Valencian',
  'vietnamese': 'Vietnamese',
  'welsh': 'Welsh',
  'wolof': 'Wolof',
  'yoruba': 'Yoruba',
};
